name: Auto Deploy OCI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy by SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/www/html
            git pull origin main
            sudo chown -R opc:opc /var/www/html
            sudo systemctl reload httpd
